name: CI/CD for Python App

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: PYTHONPATH=. pytest

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t spz_lab7 .


  deploy-to-prod:
    needs: docker-build
    runs-on: ubuntu-latest
    environment:
      name: production
      # Увімкни manual approval в GitHub → Settings → Environments → production
    steps:
      - name: Simulate deploy
        run: echo "🚀 Production deploy approved and simulated!"